import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Provider from './_trpc/Provider'
import 'tw-elements/dist/css/tw-elements.min.css'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Provider>{children}</Provider>
			</body>
		</html>
	)
}
